### ISSUE TITLE
Almost orthogonal lines

### ISSUE THREAD

**Issue by eweracs** [nnttttyyppee/NT-Somic#1]
### ruble
<img width="602" alt="image" src="https://user-images.githubusercontent.com/51919489/220111840-a92c0992-d99b-4e20-8a7f-d353e6394b66.png">

### Ylongcyr
<img width="687" alt="image" src="https://user-images.githubusercontent.com/51919489/220111954-3947edbe-4077-4166-a7b2-c10a0a40924b.png">

### numbersign
<img width="424" alt="image" src="https://user-images.githubusercontent.com/51919489/220112062-41f7dbd1-3f34-46c9-aacc-cc79f31fd73f.png">

### shacyr
<img width="304" alt="image" src="https://user-images.githubusercontent.com/51919489/220112597-54ffca00-fd94-49de-ac43-38aecac09c66.png">

**Comment by ravid-dubsteper** [comment]
thanks for your issue! we fixed it

**Comment by aencaster** [comment]
fixed in v0.6.1
